# -*- coding: utf-8 -*-
{
    'name': 'Averigo Base',
    'version': '18.0.1.0.0',
    'category': '',
    'summary': 'Base Module For Averigo',
    'description': """This module setups the base for Averigo.""",
    'author': 'Cybrosys Techno Solutions',
    'company': 'Cybrosys Techno Solutions',
    'maintainer': 'Cybrosys Techno Solutions',
    'website': 'https://www.cybrosys.com',
    'depends': ['averigo_debranding', 'stock'],
    'data': [
        'security/user_groups.xml',
        'data/data.xml',
        'data/zip.county.csv',
        'security/base_security.xml',
        'security/ir.model.access.csv',
        'views/res_company_views.xml',
        'views/res_users_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            "https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/fancybox/fancybox.umd.js",
            "https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/fancybox/fancybox.css",
            'base_averigo/static/src/js/booleanButtonWidget/booleanButtonWidget.js',
            'base_averigo/static/src/js/booleanButtonWidget/booleanButtonWidget.xml',
            'base_averigo/static/src/js/chatter.js',
            'base_averigo/static/src/js/many2many_tags_field.js',
            "base_averigo/static/src/js/imagePreview/image_preview.js",
            "base_averigo/static/src/js/imagePreview/image_preview.xml",
            "base_averigo/static/src/js/passwordEyeIconWidget/passwordEyeIconWidget.js",
            "base_averigo/static/src/js/passwordEyeIconWidget/passwordEyeIconWidget.xml",
            'base_averigo/static/src/js/one2manyNavigation/One2ManyWidget.js',
            'base_averigo/static/src/js/one2manyNavigation/One2ManyWidget.xml',
            'base_averigo/static/src/js/one2manyNavigation/navigateOne2many.scss',
        ],
    },
    'license': 'AGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
    'pre_init_hook': 'install_uninstall_module',
    'post_init_hook': 'add_group_to_user',
    'uninstall_hook': 'remove_group_from_user',
}
